// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6heSVZJTnV1iUyAN_SAGds3LxPfHIzE',
    appId: '1:102081493712:web:1c403cfc68425be5d87cd5',
    messagingSenderId: '102081493712',
    projectId: 'expensetracker-3ffb4',
    authDomain: 'expensetracker-3ffb4.firebaseapp.com',
    storageBucket: 'expensetracker-3ffb4.firebasestorage.app',
    measurementId: 'G-ZM9H7X4E3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABnNkgEf_5q9SA9YwtuPg2N9vpvV8m-c',
    appId: '1:102081493712:android:7b6e21fda2967b5dd87cd5',
    messagingSenderId: '102081493712',
    projectId: 'expensetracker-3ffb4',
    storageBucket: 'expensetracker-3ffb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPwQccR7etZQZF6OLf2Yvx8v7_msqHaVs',
    appId: '1:102081493712:ios:8c2ed4a5dd00a61cd87cd5',
    messagingSenderId: '102081493712',
    projectId: 'expensetracker-3ffb4',
    storageBucket: 'expensetracker-3ffb4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPwQccR7etZQZF6OLf2Yvx8v7_msqHaVs',
    appId: '1:102081493712:ios:8c2ed4a5dd00a61cd87cd5',
    messagingSenderId: '102081493712',
    projectId: 'expensetracker-3ffb4',
    storageBucket: 'expensetracker-3ffb4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6heSVZJTnV1iUyAN_SAGds3LxPfHIzE',
    appId: '1:102081493712:web:8a54a80acb265e67d87cd5',
    messagingSenderId: '102081493712',
    projectId: 'expensetracker-3ffb4',
    authDomain: 'expensetracker-3ffb4.firebaseapp.com',
    storageBucket: 'expensetracker-3ffb4.firebasestorage.app',
    measurementId: 'G-7PXT9844P9',
  );
}
